version: "3.9"

volumes:
  manticore_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MANTICORE_DATA_PATH:-./data/manticore}
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config

networks:
  fs-indexer:
    driver: bridge

services:
  manticore:
    image: manticoresearch/manticore:latest
    container_name: fs-manticore
    restart: unless-stopped
    ports:
      - "${MANTICORE_HTTP_PORT:-9308}:9308"
      - "${MANTICORE_MYSQL_PORT:-9306}:9306"
    environment:
      - EXTRA=1
    volumes:
      - manticore_data:/var/lib/manticore
    networks:
      - fs-indexer
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9308/cli?cmd=SHOW%20TABLES"]
      interval: 30s
      timeout: 3s
      retries: 10

  bootstrap:
    image: python:3.12-slim
    depends_on:
      manticore:
        condition: service_healthy
    networks:
      - fs-indexer
    volumes:
      - ./scripts/bootstrap.py:/bootstrap.py:ro
    command: ["python", "/bootstrap.py"]
    restart: "no"

  indexer:
    build: ./indexer
    image: local/fs-indexer:latest
    container_name: fs-indexer
    depends_on:
      manticore:
        condition: service_healthy
      bootstrap:
        condition: service_completed_successfully
    environment:
      - MANTICORE_URL=http://manticore:9308/sql?mode=raw
      - SCAN_ROOTS=${SCAN_ROOTS:-/data}
      - ROOT_NAME=${ROOT_NAME:-data}
      - EXCLUDES_FILE=/app/config/excludes.txt
      - STABILITY_SEC=${STABILITY_SEC:-30}
      - BATCH_SIZE=${BATCH_SIZE:-2000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - type: bind
        source: ${HOST_PATH:-/home}
        target: /data
        read_only: true
      - config:/app/config:ro
    networks:
      - fs-indexer
    restart: "no"

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: fs-scheduler
    depends_on:
      - indexer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cron/config.ini:/etc/ofelia/config.ini:ro
    networks:
      - fs-indexer
    restart: unless-stopped

  search-api:
    build: ./api
    image: local/fs-search-api:latest
    container_name: fs-search-api
    depends_on:
      manticore:
        condition: service_healthy
      bootstrap:
        condition: service_completed_successfully
    environment:
      - MANTICORE_URL=http://manticore:9308/sql?mode=raw
      - DEFAULT_PAGE_SIZE=${DEFAULT_PAGE_SIZE:-50}
      - MAX_PAGE_SIZE=${MAX_PAGE_SIZE:-500}
      - API_PORT=8080
    ports:
      - "${API_PORT:-8080}:8080"
    networks:
      - fs-indexer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  web:
    build: ./web
    image: local/fs-web:latest
    container_name: fs-web
    depends_on:
      - search-api
    ports:
      - "${WEB_PORT:-8081}:80"
    networks:
      - fs-indexer
    restart: unless-stopped
    environment:
      - API_URL=http://localhost:${API_PORT:-8080}