# InterFuser Agent Configuration
model_type: interfuser
model_path: /workspace/leaderboard/team_code/interfuser/interfuser.pth.tar
external_config: /workspace/leaderboard/team_code/interfuser/interfuser_config.py

model_config:
  architecture: interfuser_baseline
  skip_frames: 1  # InterFuser typically processes every other frame
  momentum: 0.95  # For traffic meta moving average

# Exact sensor configuration from interfuser_agent.py
sensors:
  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    width: 800
    height: 600
    fov: 100
    id: rgb

  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: -60.0
    width: 400
    height: 300
    fov: 100
    id: rgb_left

  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 60.0
    width: 400
    height: 300
    fov: 100
    id: rgb_right

  - type: sensor.lidar.ray_cast
    x: 1.3
    y: 0.0
    z: 2.5
    roll: 0.0
    pitch: 0.0
    yaw: -90.0
    id: lidar

  - type: sensor.other.imu
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    sensor_tick: 0.05
    id: imu

  - type: sensor.other.gnss
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    sensor_tick: 0.01
    id: gps

  - type: sensor.speedometer
    reading_frequency: 20
    id: speed

control:
  target_speed: 30.0
  brake_threshold: 0.5
  steer_damping: 0.3