# base config for policies run as an external client (run_vavam.sh) on our PAI scenes
realcar_path: /home/netai/jeykang/NetAI-Digital-Twin/Lakehouse/Iceberg/evaluation/hugsim/data/3DRealCar
model_base: /home/netai/jeykang/NetAI-Digital-Twin/Lakehouse/Iceberg/evaluation/hugsim/data/scenes/pai
uniad_path: /unused/UniAD_Sim/tools/e2e.sh
vad_path: /unused/VAD_Sim/tools/e2e.sh
ltf_path: /home/netai/jeykang/NetAI-Digital-Twin/Lakehouse/Iceberg/evaluation/hugsim/clients/external_client.sh
output_dir: /home/netai/jeykang/NetAI-Digital-Twin/Lakehouse/Iceberg/evaluation/hugsim/runs/pai_vavam_
HD_map:
  path: /unused/nuScenes/raw/Trainval
  version: nusc_trainval
